plugins {
    id 'groovy'
    id 'java-gradle-plugin'
    id 'maven-publish'
}

group = 'org.psilynx.psikit'
version = '0.1.0-beta2'

repositories {
    gradlePluginPortal()
    google()
    mavenCentral()
}

dependencies {
    implementation gradleApi()
    implementation localGroovy()
}

gradlePlugin {
    plugins {
        psiKitBuildInfo {
            id = 'org.psilynx.psikit.buildinfo'
            implementationClass = 'org.psilynx.psikit.gradle.PsiKitBuildInfoPlugin'
        }
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
            artifactId = 'psikit-buildinfo-gradle-plugin'
        }
    }
}
