plugins {
    id 'application'
    id 'java'
}

group = 'org.psilynx.psikit'
version = '0.1.0-beta2'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':core')
}

java {
    sourceCompatibility JavaVersion.VERSION_11
    targetCompatibility JavaVersion.VERSION_11
}

application {
    mainClass = 'org.psilynx.psikit.tools.ToolsMain'
}
